language: c

os:
- linux

compiler:
- gcc

script:
- cmake .
- make
- make test

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get update -q && sudo apt-get install libncurses5-dev libconfig-dev libpcre3-dev ; fi
